### ISSUE TITLE
[client-v2] Insert API Implementation

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-java#1588]
```[tasklist]
### Tasks
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1603
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1604
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1605
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1606
```
