### ISSUE TITLE
[client-v2] Testing the JDBC driver

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-java#1902]
```[tasklist]
### Phase 1 - Automated Connector Tests (ETA: 11/22)
-  [x] https://github.com/ClickHouse/clickhouse-java/issues/2021 (Serge, Mark)
- [x] DBeaver Sanity Tests (Sergey)
- [x] clickhouse-r2dbc (Mark)
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1957
- [x] ~~Advanced example (Paul)~~
- [x] ~~Adapt Clickbench queries (Paul)~~
```

```[tasklist]
### Phase 2 - Manual Connector Testing (ETA: 11/22)
- [x] Tableau (Manual - Mark)
- [x] TestContainers (Mark)
- [x] DataGrip (Paul)
- [x] Apache Spark (Simple example from docs - Mark)
- [x] Tableau TDVT Automated - @mzitnik @BentsiLeviav
```

**Comment by PeaStew** [comment]
missing the database parameter as per https://clickhouse.com/docs/en/integrations/tableau which means no default database is available for selection

**Comment by slvrtrn** [comment]
Metabase tests fail on the latest snapshot. 
Somewhere in the Metabase internals there is `autoCommit = false` setting

```
clojure.lang.ExceptionInfo: Error loading data: INSERT FAILED: setAutoCommit = false not supported
```
this throws in v2: https://github.com/ClickHouse/clickhouse-java/blob/5e304cba6409fbb62217ffe977c8a86fab23ca84/jdbc-v2/src/main/java/com/clickhouse/jdbc/ConnectionImpl.java#L130-L136
IMO should be just ignored with no-op, cause many standard implementations will try to set these

**Comment by chernser** [comment]
@slvrtrn 
In the new version we are trying to follow JDBC javadoc - if something is not implemented we are throwing exception. 
So we have two options: 
- create a option flag to ignore unimplemented values - the fastest solution
- implement simple "transaction" - however it will work only when we build SQL as string. In the future it will not work when we stream data to server (we are not going to support transactions very soon or emulate them on client side)

**Comment by GEORGE-BOAST** [comment]
> missing the database parameter as per https://clickhouse.com/docs/en/integrations/tableau which means no default database is available for selection

What is the solution here? I am trying to setup tableau cloud (on desktop) to connect to my xxx database on clickhouse and no tables appear.

**Comment by mshustov** [comment]
@GEORGE-BOAST what driver version do you use? Could you fill in a new bug report?

**Comment by GEORGE-BOAST** [comment]
> do

I am using the latest JDBC driver with the latest version of tableau desktop. 

I cannot connect using SSL, when not having said box checked, I can connect, however no tables show.

Example;

Code: 62. DB::Exception: Syntax error: failed at position 11 ('.'): .tree_lst;. Expected end of query. (SYNTAX_ERROR) (version 24.11.1.2557 (official build))
Unable to connect to the ClickHouse JDBC by ClickHouse, Inc. server “172.X.X.X”. Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.3.1
For support, contact ClickHouse, Inc..

**Comment by slvrtrn** [comment]
> In the new version we are trying to follow JDBC javadoc - if something is not implemented we are throwing exception.
> So we have two options:
> 
> So we have two options:
>
> - create a option flag to ignore unimplemented values - the fastest solution
> - implement simple "transaction" - however it will work only when we build SQL as string. In the future it will not work when we stream data to server (we are not going to support transactions very soon or emulate them on client side)

As a user, I think my preferred solution is no-op in case of unsupported standard things. So I guess option one is good.

**Comment by mshustov** [comment]
> Code: 62. DB::Exception: Syntax error: failed at position 11 ('.'): .tree_lst;. Expected end of query. (SYNTAX_ERROR) (version 24.11.1.2557 (official build))

AFAIK neither version of the driver modifies the query. please fill a bug report and include the failing query, which you can find in clickhouse [system.query_log](https://clickhouse.com/docs/en/operations/system-tables/query_log)
