### ISSUE TITLE
[client-v2] JDBC V2 Release

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-java#1929]
```[tasklist]
### Tasks (0.8.0)
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1902
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1974
- [x] Version Matrix
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1985
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1975
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/1973
- [ ] https://github.com/ClickHouse/clickhouse-java/issues/2021
- [ ] https://github.com/ClickHouse/clickhouse-docs/pull/3071
- [ ] https://github.com/ClickHouse/clickhouse-java/pull/2083
```

**Comment by mshustov** [comment]
Do these tasks belong to the current issue scope? https://github.com/ClickHouse/clickhouse-java/issues?q=is%3Aissue+is%3Aopen+label%3Ajdbc-v2
